title: Arcoíris Collective
description: Promoting ethical Mexican crafts and supporting Zapatista communities.
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: "" # Leave blank unless you are hosting under a subdirectory
url: "https://arcoiriscollective.github.io" # Update with custom domain later
